### ISSUE TITLE
Please update the code for downloading latest_release dbsnp. Thank you!

### ISSUE THREAD

**Issue by CaoLuYao98** [zhanghaoyang0/rsidmap#1]
When I used the code to download latest_release dbsnp, I met:

wget -c https://ftp.ncbi.nlm.nih.gov/snp/latest_release/VCF/GCF_000001405.25.gz -P dbsnp/
--2023-03-14 14:09:08--  https://ftp.ncbi.nlm.nih.gov/snp/latest_release/VCF/GCF_000001405.25.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 165.112.9.229, 165.112.9.228, 2607:f220:41e:250::7, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|165.112.9.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25405089331 (24G) [application/x-gzip]
dbsnp: File existsdbsnp/GCF_000001405.25.gz: No such file or directory

I suppose I met the situation you metioned "dbsnp is updated", so please update the code. Thanks a lot!

**Comment by zhanghaoyang0** [comment]
Hi, thank you for your interest~

It is my mistake, `dbnsnp` is not a folder, so you cannot download data into it successfully.

Please re-download the tool and try again.

```
git clone https://github.com/zhanghaoyang0/rsidmap.git
cd rsidmap

url="https://ftp.ncbi.nlm.nih.gov/snp/latest_release/VCF/"
dbsnp_hg19="GCF_000001405.25"
dbsnp_hg38="GCF_000001405.40"

# for hg 19
wget -c ${url}${dbsnp_hg19}.gz -P dbsnp/
wget -c ${url}${dbsnp_hg19}.gz.md5 -P dbsnp/
wget -c ${url}${dbsnp_hg19}.gz.tbi -P dbsnp/
wget -c ${url}${dbsnp_hg19}.gz.tbi.md5 -P dbsnp/

# for hg38
wget -c ${url}${dbsnp_hg38}.gz -P dbsnp/
wget -c ${url}${dbsnp_hg38}.gz.md5 -P dbsnp/
wget -c ${url}${dbsnp_hg38}.gz.tbi -P dbsnp/
wget -c ${url}${dbsnp_hg38}.gz.tbi.md5 -P dbsnp/

# check md5sum
cd dbsnp
md5sum -c ${dbsnp_hg19}.gz.md5
md5sum -c ${dbsnp_hg19}.gz.tbi.md5
md5sum -c ${dbsnp_hg38}.gz.md5
md5sum -c ${dbsnp_hg38}.gz.tbi.md5
cd ../
```
And below is the same~

**Comment by CaoLuYao98** [comment]
The updated code is feasible~Thank you!
