### ISSUE TITLE
KeyError: '19'

### ISSUE THREAD

**Issue by mcamenc** [zhanghaoyang0/rsidmap#2]
Hi! Follow all the steps for cloning and download dbsnp database and everything was fine. 

However, when running rsidmap_v2 got this:

`python ./rsidmap/code/rsid
map_v2.py --build 19 --chr_col Chromosome --pos_col Position --r
ef_col AlternateAllele --alt_col EffectAllele --file_gwas ./data
/GWAS_sumstats/kneehip_oa.txt --file_out ./data/GWAS_sumstats_kneehip_oa_rsids.txt
Setting:
build: 19
chr_col: Chromosome
pos_col: Position
ref_col: AlternateAllele
alt_col: EffectAllele
file_gwas: ./data/GWAS_sumstats/kneehip_oa.txt
file_out: ./data/GWAS_sumstats_kneehip_oa_rsids.txt
exact_map: False
making dnsnp dict ...
23763393 unique and valid snp.
Traceback (most recent call last):
  File "./rsidmap/code/rsidmap_v2.py", line 102, in <module>
    with gzip.open(file_dbsnp[build], 'rt') as f:
KeyError: '19'`

GWAS file can be download from: https://personal.broadinstitute.org/ryank/KP.Format.GO.FILTER.GW.KneeHipOA.FULL.09052019.txt.gz

Any idea of how can I solve this?

**Comment by zhanghaoyang0** [comment]
Hi, 

Please change "--build 19" to "--build hg19" and retry again.

**Comment by mcamenc** [comment]
God! Your right... such a silly error! 

Thanks so much. That worked.
